global:
  resolve_timeout: 5m
  slack_api_url: 'your_slack_webhook_url'


route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
receivers:
- name: 'web.hook'
  # webhook_configs:
  # - url: 'http://127.0.0.1:5001/'
  slack_configs:
    - channel: "alerting"
# inhibit_rules:
#   - source_match:
#       severity: 'critical'
#     target_match:
#       severity: 'warning'
#     equal: ['alertname', 'dev', 'instance']
