apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.9.1
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
          ports:
            - name: prometheus
              containerPort: 8080
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-config
